/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedProfesseurRouteImport } from './routes/_authenticated/professeur'
import { Route as AuthenticatedPartenaireRouteImport } from './routes/_authenticated/partenaire'
import { Route as AuthenticatedEtudiantRouteImport } from './routes/_authenticated/etudiant'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfesseurPartenairesRouteImport } from './routes/_authenticated/professeur.partenaires'
import { Route as AuthenticatedEtudiantParcoursRouteImport } from './routes/_authenticated/etudiant.parcours'
import { Route as AuthenticatedEtudiantGroupeRouteImport } from './routes/_authenticated/etudiant.groupe'
import { Route as AuthenticatedEtudiantCarnetRouteImport } from './routes/_authenticated/etudiant.carnet'
import { Route as AuthenticatedEtudiantBadgesRouteImport } from './routes/_authenticated/etudiant.badges'
import { Route as AuthenticatedAdminPartenairesRouteImport } from './routes/_authenticated/admin.partenaires'
import { Route as AuthenticatedAdminParcoursRouteImport } from './routes/_authenticated/admin.parcours'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfesseurRoute = AuthenticatedProfesseurRouteImport.update({
  id: '/professeur',
  path: '/professeur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartenaireRoute = AuthenticatedPartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtudiantRoute = AuthenticatedEtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfesseurPartenairesRoute =
  AuthenticatedProfesseurPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedEtudiantParcoursRoute =
  AuthenticatedEtudiantParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantGroupeRoute =
  AuthenticatedEtudiantGroupeRouteImport.update({
    id: '/groupe',
    path: '/groupe',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantCarnetRoute =
  AuthenticatedEtudiantCarnetRouteImport.update({
    id: '/carnet',
    path: '/carnet',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantBadgesRoute =
  AuthenticatedEtudiantBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedAdminPartenairesRoute =
  AuthenticatedAdminPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParcoursRoute =
  AuthenticatedAdminParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/partenaire': typeof AuthenticatedPartenaireRoute
  '/professeur': typeof AuthenticatedProfesseurRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/parcours': typeof AuthenticatedAdminParcoursRoute
  '/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/etudiant/badges': typeof AuthenticatedEtudiantBadgesRoute
  '/etudiant/carnet': typeof AuthenticatedEtudiantCarnetRoute
  '/etudiant/groupe': typeof AuthenticatedEtudiantGroupeRoute
  '/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/professeur/partenaires': typeof AuthenticatedProfesseurPartenairesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/partenaire': typeof AuthenticatedPartenaireRoute
  '/professeur': typeof AuthenticatedProfesseurRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/parcours': typeof AuthenticatedAdminParcoursRoute
  '/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/etudiant/badges': typeof AuthenticatedEtudiantBadgesRoute
  '/etudiant/carnet': typeof AuthenticatedEtudiantCarnetRoute
  '/etudiant/groupe': typeof AuthenticatedEtudiantGroupeRoute
  '/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/professeur/partenaires': typeof AuthenticatedProfesseurPartenairesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/_authenticated/partenaire': typeof AuthenticatedPartenaireRoute
  '/_authenticated/professeur': typeof AuthenticatedProfesseurRouteWithChildren
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/parcours': typeof AuthenticatedAdminParcoursRoute
  '/_authenticated/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/_authenticated/etudiant/badges': typeof AuthenticatedEtudiantBadgesRoute
  '/_authenticated/etudiant/carnet': typeof AuthenticatedEtudiantCarnetRoute
  '/_authenticated/etudiant/groupe': typeof AuthenticatedEtudiantGroupeRoute
  '/_authenticated/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/_authenticated/professeur/partenaires': typeof AuthenticatedProfesseurPartenairesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/app'
    | '/etudiant'
    | '/partenaire'
    | '/professeur'
    | '/profil'
    | '/auth/reset-password'
    | '/admin/parcours'
    | '/admin/partenaires'
    | '/etudiant/badges'
    | '/etudiant/carnet'
    | '/etudiant/groupe'
    | '/etudiant/parcours'
    | '/professeur/partenaires'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/app'
    | '/etudiant'
    | '/partenaire'
    | '/professeur'
    | '/profil'
    | '/auth/reset-password'
    | '/admin/parcours'
    | '/admin/partenaires'
    | '/etudiant/badges'
    | '/etudiant/carnet'
    | '/etudiant/groupe'
    | '/etudiant/parcours'
    | '/professeur/partenaires'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/etudiant'
    | '/_authenticated/partenaire'
    | '/_authenticated/professeur'
    | '/_authenticated/profil'
    | '/auth/reset-password'
    | '/_authenticated/admin/parcours'
    | '/_authenticated/admin/partenaires'
    | '/_authenticated/etudiant/badges'
    | '/_authenticated/etudiant/carnet'
    | '/_authenticated/etudiant/groupe'
    | '/_authenticated/etudiant/parcours'
    | '/_authenticated/professeur/partenaires'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professeur': {
      id: '/_authenticated/professeur'
      path: '/professeur'
      fullPath: '/professeur'
      preLoaderRoute: typeof AuthenticatedProfesseurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaire': {
      id: '/_authenticated/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof AuthenticatedPartenaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etudiant': {
      id: '/_authenticated/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof AuthenticatedEtudiantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professeur/partenaires': {
      id: '/_authenticated/professeur/partenaires'
      path: '/partenaires'
      fullPath: '/professeur/partenaires'
      preLoaderRoute: typeof AuthenticatedProfesseurPartenairesRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/etudiant/parcours': {
      id: '/_authenticated/etudiant/parcours'
      path: '/parcours'
      fullPath: '/etudiant/parcours'
      preLoaderRoute: typeof AuthenticatedEtudiantParcoursRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/groupe': {
      id: '/_authenticated/etudiant/groupe'
      path: '/groupe'
      fullPath: '/etudiant/groupe'
      preLoaderRoute: typeof AuthenticatedEtudiantGroupeRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/carnet': {
      id: '/_authenticated/etudiant/carnet'
      path: '/carnet'
      fullPath: '/etudiant/carnet'
      preLoaderRoute: typeof AuthenticatedEtudiantCarnetRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/badges': {
      id: '/_authenticated/etudiant/badges'
      path: '/badges'
      fullPath: '/etudiant/badges'
      preLoaderRoute: typeof AuthenticatedEtudiantBadgesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/admin/partenaires': {
      id: '/_authenticated/admin/partenaires'
      path: '/partenaires'
      fullPath: '/admin/partenaires'
      preLoaderRoute: typeof AuthenticatedAdminPartenairesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parcours': {
      id: '/_authenticated/admin/parcours'
      path: '/parcours'
      fullPath: '/admin/parcours'
      preLoaderRoute: typeof AuthenticatedAdminParcoursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminParcoursRoute: typeof AuthenticatedAdminParcoursRoute
  AuthenticatedAdminPartenairesRoute: typeof AuthenticatedAdminPartenairesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminParcoursRoute: AuthenticatedAdminParcoursRoute,
  AuthenticatedAdminPartenairesRoute: AuthenticatedAdminPartenairesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEtudiantRouteChildren {
  AuthenticatedEtudiantBadgesRoute: typeof AuthenticatedEtudiantBadgesRoute
  AuthenticatedEtudiantCarnetRoute: typeof AuthenticatedEtudiantCarnetRoute
  AuthenticatedEtudiantGroupeRoute: typeof AuthenticatedEtudiantGroupeRoute
  AuthenticatedEtudiantParcoursRoute: typeof AuthenticatedEtudiantParcoursRoute
}

const AuthenticatedEtudiantRouteChildren: AuthenticatedEtudiantRouteChildren = {
  AuthenticatedEtudiantBadgesRoute: AuthenticatedEtudiantBadgesRoute,
  AuthenticatedEtudiantCarnetRoute: AuthenticatedEtudiantCarnetRoute,
  AuthenticatedEtudiantGroupeRoute: AuthenticatedEtudiantGroupeRoute,
  AuthenticatedEtudiantParcoursRoute: AuthenticatedEtudiantParcoursRoute,
}

const AuthenticatedEtudiantRouteWithChildren =
  AuthenticatedEtudiantRoute._addFileChildren(
    AuthenticatedEtudiantRouteChildren,
  )

interface AuthenticatedProfesseurRouteChildren {
  AuthenticatedProfesseurPartenairesRoute: typeof AuthenticatedProfesseurPartenairesRoute
}

const AuthenticatedProfesseurRouteChildren: AuthenticatedProfesseurRouteChildren =
  {
    AuthenticatedProfesseurPartenairesRoute:
      AuthenticatedProfesseurPartenairesRoute,
  }

const AuthenticatedProfesseurRouteWithChildren =
  AuthenticatedProfesseurRoute._addFileChildren(
    AuthenticatedProfesseurRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedEtudiantRoute: typeof AuthenticatedEtudiantRouteWithChildren
  AuthenticatedPartenaireRoute: typeof AuthenticatedPartenaireRoute
  AuthenticatedProfesseurRoute: typeof AuthenticatedProfesseurRouteWithChildren
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedEtudiantRoute: AuthenticatedEtudiantRouteWithChildren,
  AuthenticatedPartenaireRoute: AuthenticatedPartenaireRoute,
  AuthenticatedProfesseurRoute: AuthenticatedProfesseurRouteWithChildren,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
