/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedProfesseurRouteImport } from './routes/_authenticated/professeur'
import { Route as AuthenticatedPartenaireRouteImport } from './routes/_authenticated/partenaire'
import { Route as AuthenticatedEtudiantRouteImport } from './routes/_authenticated/etudiant'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfesseurValidationsRouteImport } from './routes/_authenticated/professeur.validations'
import { Route as AuthenticatedProfesseurProlongationsRouteImport } from './routes/_authenticated/professeur.prolongations'
import { Route as AuthenticatedProfesseurPartenairesRouteImport } from './routes/_authenticated/professeur.partenaires'
import { Route as AuthenticatedProfesseurParcoursRouteImport } from './routes/_authenticated/professeur.parcours'
import { Route as AuthenticatedProfesseurModulesRouteImport } from './routes/_authenticated/professeur.modules'
import { Route as AuthenticatedProfesseurMissionsRouteImport } from './routes/_authenticated/professeur.missions'
import { Route as AuthenticatedProfesseurEtudiantsRouteImport } from './routes/_authenticated/professeur.etudiants'
import { Route as AuthenticatedPartenaireParcoursRouteImport } from './routes/_authenticated/partenaire.parcours'
import { Route as AuthenticatedPartenaireMissionsRouteImport } from './routes/_authenticated/partenaire.missions'
import { Route as AuthenticatedPartenaireEtudiantsRouteImport } from './routes/_authenticated/partenaire.etudiants'
import { Route as AuthenticatedEtudiantSessionsRouteImport } from './routes/_authenticated/etudiant.sessions'
import { Route as AuthenticatedEtudiantParcoursRouteImport } from './routes/_authenticated/etudiant.parcours'
import { Route as AuthenticatedEtudiantNotificationsRouteImport } from './routes/_authenticated/etudiant.notifications'
import { Route as AuthenticatedEtudiantGroupeRouteImport } from './routes/_authenticated/etudiant.groupe'
import { Route as AuthenticatedEtudiantCarnetRouteImport } from './routes/_authenticated/etudiant.carnet'
import { Route as AuthenticatedEtudiantBadgesRouteImport } from './routes/_authenticated/etudiant.badges'
import { Route as AuthenticatedAdminValidationsRouteImport } from './routes/_authenticated/admin.validations'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin.sessions'
import { Route as AuthenticatedAdminProlongationsRouteImport } from './routes/_authenticated/admin.prolongations'
import { Route as AuthenticatedAdminProfesseursRouteImport } from './routes/_authenticated/admin.professeurs'
import { Route as AuthenticatedAdminPartenairesRouteImport } from './routes/_authenticated/admin.partenaires'
import { Route as AuthenticatedAdminParcoursRouteImport } from './routes/_authenticated/admin.parcours'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin.parametres'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMissionsRouteImport } from './routes/_authenticated/admin.missions'
import { Route as AuthenticatedAdminGroupesRouteImport } from './routes/_authenticated/admin.groupes'
import { Route as AuthenticatedAdminEtudiantsRouteImport } from './routes/_authenticated/admin.etudiants'
import { Route as AuthenticatedAdminCahierDeTexteRouteImport } from './routes/_authenticated/admin.cahier-de-texte'
import { Route as AuthenticatedAdminBibliothequeRouteImport } from './routes/_authenticated/admin.bibliotheque'
import { Route as AuthenticatedAdminBadgesRouteImport } from './routes/_authenticated/admin.badges'
import { Route as AuthenticatedProfesseurParcoursParcoursIdRouteImport } from './routes/_authenticated/professeur.parcours.$parcoursId'
import { Route as AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRouteImport } from './routes/_authenticated/professeur.carnet.$etudiantId.$parcoursId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfesseurRoute = AuthenticatedProfesseurRouteImport.update({
  id: '/professeur',
  path: '/professeur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartenaireRoute = AuthenticatedPartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtudiantRoute = AuthenticatedEtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfesseurValidationsRoute =
  AuthenticatedProfesseurValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedProfesseurProlongationsRoute =
  AuthenticatedProfesseurProlongationsRouteImport.update({
    id: '/prolongations',
    path: '/prolongations',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedProfesseurPartenairesRoute =
  AuthenticatedProfesseurPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedProfesseurParcoursRoute =
  AuthenticatedProfesseurParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedProfesseurModulesRoute =
  AuthenticatedProfesseurModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedProfesseurMissionsRoute =
  AuthenticatedProfesseurMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedProfesseurEtudiantsRoute =
  AuthenticatedProfesseurEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)
const AuthenticatedPartenaireParcoursRoute =
  AuthenticatedPartenaireParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireMissionsRoute =
  AuthenticatedPartenaireMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireEtudiantsRoute =
  AuthenticatedPartenaireEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedEtudiantSessionsRoute =
  AuthenticatedEtudiantSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantParcoursRoute =
  AuthenticatedEtudiantParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantNotificationsRoute =
  AuthenticatedEtudiantNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantGroupeRoute =
  AuthenticatedEtudiantGroupeRouteImport.update({
    id: '/groupe',
    path: '/groupe',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantCarnetRoute =
  AuthenticatedEtudiantCarnetRouteImport.update({
    id: '/carnet',
    path: '/carnet',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantBadgesRoute =
  AuthenticatedEtudiantBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedAdminValidationsRoute =
  AuthenticatedAdminValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProlongationsRoute =
  AuthenticatedAdminProlongationsRouteImport.update({
    id: '/prolongations',
    path: '/prolongations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfesseursRoute =
  AuthenticatedAdminProfesseursRouteImport.update({
    id: '/professeurs',
    path: '/professeurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartenairesRoute =
  AuthenticatedAdminPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParcoursRoute =
  AuthenticatedAdminParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMissionsRoute =
  AuthenticatedAdminMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGroupesRoute =
  AuthenticatedAdminGroupesRouteImport.update({
    id: '/groupes',
    path: '/groupes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEtudiantsRoute =
  AuthenticatedAdminEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCahierDeTexteRoute =
  AuthenticatedAdminCahierDeTexteRouteImport.update({
    id: '/cahier-de-texte',
    path: '/cahier-de-texte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBibliothequeRoute =
  AuthenticatedAdminBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBadgesRoute =
  AuthenticatedAdminBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProfesseurParcoursParcoursIdRoute =
  AuthenticatedProfesseurParcoursParcoursIdRouteImport.update({
    id: '/$parcoursId',
    path: '/$parcoursId',
    getParentRoute: () => AuthenticatedProfesseurParcoursRoute,
  } as any)
const AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute =
  AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRouteImport.update({
    id: '/carnet/$etudiantId/$parcoursId',
    path: '/carnet/$etudiantId/$parcoursId',
    getParentRoute: () => AuthenticatedProfesseurRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/partenaire': typeof AuthenticatedPartenaireRouteWithChildren
  '/professeur': typeof AuthenticatedProfesseurRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/bibliotheque': typeof AuthenticatedAdminBibliothequeRoute
  '/admin/cahier-de-texte': typeof AuthenticatedAdminCahierDeTexteRoute
  '/admin/etudiants': typeof AuthenticatedAdminEtudiantsRoute
  '/admin/groupes': typeof AuthenticatedAdminGroupesRoute
  '/admin/missions': typeof AuthenticatedAdminMissionsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/parcours': typeof AuthenticatedAdminParcoursRoute
  '/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/admin/prolongations': typeof AuthenticatedAdminProlongationsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/etudiant/badges': typeof AuthenticatedEtudiantBadgesRoute
  '/etudiant/carnet': typeof AuthenticatedEtudiantCarnetRoute
  '/etudiant/groupe': typeof AuthenticatedEtudiantGroupeRoute
  '/etudiant/notifications': typeof AuthenticatedEtudiantNotificationsRoute
  '/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/etudiant/sessions': typeof AuthenticatedEtudiantSessionsRoute
  '/partenaire/etudiants': typeof AuthenticatedPartenaireEtudiantsRoute
  '/partenaire/missions': typeof AuthenticatedPartenaireMissionsRoute
  '/partenaire/parcours': typeof AuthenticatedPartenaireParcoursRoute
  '/professeur/etudiants': typeof AuthenticatedProfesseurEtudiantsRoute
  '/professeur/missions': typeof AuthenticatedProfesseurMissionsRoute
  '/professeur/modules': typeof AuthenticatedProfesseurModulesRoute
  '/professeur/parcours': typeof AuthenticatedProfesseurParcoursRouteWithChildren
  '/professeur/partenaires': typeof AuthenticatedProfesseurPartenairesRoute
  '/professeur/prolongations': typeof AuthenticatedProfesseurProlongationsRoute
  '/professeur/validations': typeof AuthenticatedProfesseurValidationsRoute
  '/professeur/parcours/$parcoursId': typeof AuthenticatedProfesseurParcoursParcoursIdRoute
  '/professeur/carnet/$etudiantId/$parcoursId': typeof AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/partenaire': typeof AuthenticatedPartenaireRouteWithChildren
  '/professeur': typeof AuthenticatedProfesseurRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/bibliotheque': typeof AuthenticatedAdminBibliothequeRoute
  '/admin/cahier-de-texte': typeof AuthenticatedAdminCahierDeTexteRoute
  '/admin/etudiants': typeof AuthenticatedAdminEtudiantsRoute
  '/admin/groupes': typeof AuthenticatedAdminGroupesRoute
  '/admin/missions': typeof AuthenticatedAdminMissionsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/parcours': typeof AuthenticatedAdminParcoursRoute
  '/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/admin/prolongations': typeof AuthenticatedAdminProlongationsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/etudiant/badges': typeof AuthenticatedEtudiantBadgesRoute
  '/etudiant/carnet': typeof AuthenticatedEtudiantCarnetRoute
  '/etudiant/groupe': typeof AuthenticatedEtudiantGroupeRoute
  '/etudiant/notifications': typeof AuthenticatedEtudiantNotificationsRoute
  '/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/etudiant/sessions': typeof AuthenticatedEtudiantSessionsRoute
  '/partenaire/etudiants': typeof AuthenticatedPartenaireEtudiantsRoute
  '/partenaire/missions': typeof AuthenticatedPartenaireMissionsRoute
  '/partenaire/parcours': typeof AuthenticatedPartenaireParcoursRoute
  '/professeur/etudiants': typeof AuthenticatedProfesseurEtudiantsRoute
  '/professeur/missions': typeof AuthenticatedProfesseurMissionsRoute
  '/professeur/modules': typeof AuthenticatedProfesseurModulesRoute
  '/professeur/parcours': typeof AuthenticatedProfesseurParcoursRouteWithChildren
  '/professeur/partenaires': typeof AuthenticatedProfesseurPartenairesRoute
  '/professeur/prolongations': typeof AuthenticatedProfesseurProlongationsRoute
  '/professeur/validations': typeof AuthenticatedProfesseurValidationsRoute
  '/professeur/parcours/$parcoursId': typeof AuthenticatedProfesseurParcoursParcoursIdRoute
  '/professeur/carnet/$etudiantId/$parcoursId': typeof AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/_authenticated/partenaire': typeof AuthenticatedPartenaireRouteWithChildren
  '/_authenticated/professeur': typeof AuthenticatedProfesseurRouteWithChildren
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/_authenticated/admin/bibliotheque': typeof AuthenticatedAdminBibliothequeRoute
  '/_authenticated/admin/cahier-de-texte': typeof AuthenticatedAdminCahierDeTexteRoute
  '/_authenticated/admin/etudiants': typeof AuthenticatedAdminEtudiantsRoute
  '/_authenticated/admin/groupes': typeof AuthenticatedAdminGroupesRoute
  '/_authenticated/admin/missions': typeof AuthenticatedAdminMissionsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/parcours': typeof AuthenticatedAdminParcoursRoute
  '/_authenticated/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/_authenticated/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/_authenticated/admin/prolongations': typeof AuthenticatedAdminProlongationsRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/_authenticated/etudiant/badges': typeof AuthenticatedEtudiantBadgesRoute
  '/_authenticated/etudiant/carnet': typeof AuthenticatedEtudiantCarnetRoute
  '/_authenticated/etudiant/groupe': typeof AuthenticatedEtudiantGroupeRoute
  '/_authenticated/etudiant/notifications': typeof AuthenticatedEtudiantNotificationsRoute
  '/_authenticated/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/_authenticated/etudiant/sessions': typeof AuthenticatedEtudiantSessionsRoute
  '/_authenticated/partenaire/etudiants': typeof AuthenticatedPartenaireEtudiantsRoute
  '/_authenticated/partenaire/missions': typeof AuthenticatedPartenaireMissionsRoute
  '/_authenticated/partenaire/parcours': typeof AuthenticatedPartenaireParcoursRoute
  '/_authenticated/professeur/etudiants': typeof AuthenticatedProfesseurEtudiantsRoute
  '/_authenticated/professeur/missions': typeof AuthenticatedProfesseurMissionsRoute
  '/_authenticated/professeur/modules': typeof AuthenticatedProfesseurModulesRoute
  '/_authenticated/professeur/parcours': typeof AuthenticatedProfesseurParcoursRouteWithChildren
  '/_authenticated/professeur/partenaires': typeof AuthenticatedProfesseurPartenairesRoute
  '/_authenticated/professeur/prolongations': typeof AuthenticatedProfesseurProlongationsRoute
  '/_authenticated/professeur/validations': typeof AuthenticatedProfesseurValidationsRoute
  '/_authenticated/professeur/parcours/$parcoursId': typeof AuthenticatedProfesseurParcoursParcoursIdRoute
  '/_authenticated/professeur/carnet/$etudiantId/$parcoursId': typeof AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/app'
    | '/etudiant'
    | '/partenaire'
    | '/professeur'
    | '/profil'
    | '/auth/reset-password'
    | '/admin/badges'
    | '/admin/bibliotheque'
    | '/admin/cahier-de-texte'
    | '/admin/etudiants'
    | '/admin/groupes'
    | '/admin/missions'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/parcours'
    | '/admin/partenaires'
    | '/admin/professeurs'
    | '/admin/prolongations'
    | '/admin/sessions'
    | '/admin/validations'
    | '/etudiant/badges'
    | '/etudiant/carnet'
    | '/etudiant/groupe'
    | '/etudiant/notifications'
    | '/etudiant/parcours'
    | '/etudiant/sessions'
    | '/partenaire/etudiants'
    | '/partenaire/missions'
    | '/partenaire/parcours'
    | '/professeur/etudiants'
    | '/professeur/missions'
    | '/professeur/modules'
    | '/professeur/parcours'
    | '/professeur/partenaires'
    | '/professeur/prolongations'
    | '/professeur/validations'
    | '/professeur/parcours/$parcoursId'
    | '/professeur/carnet/$etudiantId/$parcoursId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/app'
    | '/etudiant'
    | '/partenaire'
    | '/professeur'
    | '/profil'
    | '/auth/reset-password'
    | '/admin/badges'
    | '/admin/bibliotheque'
    | '/admin/cahier-de-texte'
    | '/admin/etudiants'
    | '/admin/groupes'
    | '/admin/missions'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/parcours'
    | '/admin/partenaires'
    | '/admin/professeurs'
    | '/admin/prolongations'
    | '/admin/sessions'
    | '/admin/validations'
    | '/etudiant/badges'
    | '/etudiant/carnet'
    | '/etudiant/groupe'
    | '/etudiant/notifications'
    | '/etudiant/parcours'
    | '/etudiant/sessions'
    | '/partenaire/etudiants'
    | '/partenaire/missions'
    | '/partenaire/parcours'
    | '/professeur/etudiants'
    | '/professeur/missions'
    | '/professeur/modules'
    | '/professeur/parcours'
    | '/professeur/partenaires'
    | '/professeur/prolongations'
    | '/professeur/validations'
    | '/professeur/parcours/$parcoursId'
    | '/professeur/carnet/$etudiantId/$parcoursId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/etudiant'
    | '/_authenticated/partenaire'
    | '/_authenticated/professeur'
    | '/_authenticated/profil'
    | '/auth/reset-password'
    | '/_authenticated/admin/badges'
    | '/_authenticated/admin/bibliotheque'
    | '/_authenticated/admin/cahier-de-texte'
    | '/_authenticated/admin/etudiants'
    | '/_authenticated/admin/groupes'
    | '/_authenticated/admin/missions'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/parcours'
    | '/_authenticated/admin/partenaires'
    | '/_authenticated/admin/professeurs'
    | '/_authenticated/admin/prolongations'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/validations'
    | '/_authenticated/etudiant/badges'
    | '/_authenticated/etudiant/carnet'
    | '/_authenticated/etudiant/groupe'
    | '/_authenticated/etudiant/notifications'
    | '/_authenticated/etudiant/parcours'
    | '/_authenticated/etudiant/sessions'
    | '/_authenticated/partenaire/etudiants'
    | '/_authenticated/partenaire/missions'
    | '/_authenticated/partenaire/parcours'
    | '/_authenticated/professeur/etudiants'
    | '/_authenticated/professeur/missions'
    | '/_authenticated/professeur/modules'
    | '/_authenticated/professeur/parcours'
    | '/_authenticated/professeur/partenaires'
    | '/_authenticated/professeur/prolongations'
    | '/_authenticated/professeur/validations'
    | '/_authenticated/professeur/parcours/$parcoursId'
    | '/_authenticated/professeur/carnet/$etudiantId/$parcoursId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professeur': {
      id: '/_authenticated/professeur'
      path: '/professeur'
      fullPath: '/professeur'
      preLoaderRoute: typeof AuthenticatedProfesseurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaire': {
      id: '/_authenticated/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof AuthenticatedPartenaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etudiant': {
      id: '/_authenticated/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof AuthenticatedEtudiantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professeur/validations': {
      id: '/_authenticated/professeur/validations'
      path: '/validations'
      fullPath: '/professeur/validations'
      preLoaderRoute: typeof AuthenticatedProfesseurValidationsRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/professeur/prolongations': {
      id: '/_authenticated/professeur/prolongations'
      path: '/prolongations'
      fullPath: '/professeur/prolongations'
      preLoaderRoute: typeof AuthenticatedProfesseurProlongationsRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/professeur/partenaires': {
      id: '/_authenticated/professeur/partenaires'
      path: '/partenaires'
      fullPath: '/professeur/partenaires'
      preLoaderRoute: typeof AuthenticatedProfesseurPartenairesRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/professeur/parcours': {
      id: '/_authenticated/professeur/parcours'
      path: '/parcours'
      fullPath: '/professeur/parcours'
      preLoaderRoute: typeof AuthenticatedProfesseurParcoursRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/professeur/modules': {
      id: '/_authenticated/professeur/modules'
      path: '/modules'
      fullPath: '/professeur/modules'
      preLoaderRoute: typeof AuthenticatedProfesseurModulesRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/professeur/missions': {
      id: '/_authenticated/professeur/missions'
      path: '/missions'
      fullPath: '/professeur/missions'
      preLoaderRoute: typeof AuthenticatedProfesseurMissionsRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/professeur/etudiants': {
      id: '/_authenticated/professeur/etudiants'
      path: '/etudiants'
      fullPath: '/professeur/etudiants'
      preLoaderRoute: typeof AuthenticatedProfesseurEtudiantsRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
    '/_authenticated/partenaire/parcours': {
      id: '/_authenticated/partenaire/parcours'
      path: '/parcours'
      fullPath: '/partenaire/parcours'
      preLoaderRoute: typeof AuthenticatedPartenaireParcoursRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/missions': {
      id: '/_authenticated/partenaire/missions'
      path: '/missions'
      fullPath: '/partenaire/missions'
      preLoaderRoute: typeof AuthenticatedPartenaireMissionsRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/etudiants': {
      id: '/_authenticated/partenaire/etudiants'
      path: '/etudiants'
      fullPath: '/partenaire/etudiants'
      preLoaderRoute: typeof AuthenticatedPartenaireEtudiantsRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/etudiant/sessions': {
      id: '/_authenticated/etudiant/sessions'
      path: '/sessions'
      fullPath: '/etudiant/sessions'
      preLoaderRoute: typeof AuthenticatedEtudiantSessionsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/parcours': {
      id: '/_authenticated/etudiant/parcours'
      path: '/parcours'
      fullPath: '/etudiant/parcours'
      preLoaderRoute: typeof AuthenticatedEtudiantParcoursRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/notifications': {
      id: '/_authenticated/etudiant/notifications'
      path: '/notifications'
      fullPath: '/etudiant/notifications'
      preLoaderRoute: typeof AuthenticatedEtudiantNotificationsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/groupe': {
      id: '/_authenticated/etudiant/groupe'
      path: '/groupe'
      fullPath: '/etudiant/groupe'
      preLoaderRoute: typeof AuthenticatedEtudiantGroupeRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/carnet': {
      id: '/_authenticated/etudiant/carnet'
      path: '/carnet'
      fullPath: '/etudiant/carnet'
      preLoaderRoute: typeof AuthenticatedEtudiantCarnetRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/badges': {
      id: '/_authenticated/etudiant/badges'
      path: '/badges'
      fullPath: '/etudiant/badges'
      preLoaderRoute: typeof AuthenticatedEtudiantBadgesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/admin/validations': {
      id: '/_authenticated/admin/validations'
      path: '/validations'
      fullPath: '/admin/validations'
      preLoaderRoute: typeof AuthenticatedAdminValidationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prolongations': {
      id: '/_authenticated/admin/prolongations'
      path: '/prolongations'
      fullPath: '/admin/prolongations'
      preLoaderRoute: typeof AuthenticatedAdminProlongationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/professeurs': {
      id: '/_authenticated/admin/professeurs'
      path: '/professeurs'
      fullPath: '/admin/professeurs'
      preLoaderRoute: typeof AuthenticatedAdminProfesseursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partenaires': {
      id: '/_authenticated/admin/partenaires'
      path: '/partenaires'
      fullPath: '/admin/partenaires'
      preLoaderRoute: typeof AuthenticatedAdminPartenairesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parcours': {
      id: '/_authenticated/admin/parcours'
      path: '/parcours'
      fullPath: '/admin/parcours'
      preLoaderRoute: typeof AuthenticatedAdminParcoursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/missions': {
      id: '/_authenticated/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AuthenticatedAdminMissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/groupes': {
      id: '/_authenticated/admin/groupes'
      path: '/groupes'
      fullPath: '/admin/groupes'
      preLoaderRoute: typeof AuthenticatedAdminGroupesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/etudiants': {
      id: '/_authenticated/admin/etudiants'
      path: '/etudiants'
      fullPath: '/admin/etudiants'
      preLoaderRoute: typeof AuthenticatedAdminEtudiantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cahier-de-texte': {
      id: '/_authenticated/admin/cahier-de-texte'
      path: '/cahier-de-texte'
      fullPath: '/admin/cahier-de-texte'
      preLoaderRoute: typeof AuthenticatedAdminCahierDeTexteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bibliotheque': {
      id: '/_authenticated/admin/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/admin/bibliotheque'
      preLoaderRoute: typeof AuthenticatedAdminBibliothequeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/badges': {
      id: '/_authenticated/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AuthenticatedAdminBadgesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/professeur/parcours/$parcoursId': {
      id: '/_authenticated/professeur/parcours/$parcoursId'
      path: '/$parcoursId'
      fullPath: '/professeur/parcours/$parcoursId'
      preLoaderRoute: typeof AuthenticatedProfesseurParcoursParcoursIdRouteImport
      parentRoute: typeof AuthenticatedProfesseurParcoursRoute
    }
    '/_authenticated/professeur/carnet/$etudiantId/$parcoursId': {
      id: '/_authenticated/professeur/carnet/$etudiantId/$parcoursId'
      path: '/carnet/$etudiantId/$parcoursId'
      fullPath: '/professeur/carnet/$etudiantId/$parcoursId'
      preLoaderRoute: typeof AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRouteImport
      parentRoute: typeof AuthenticatedProfesseurRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBadgesRoute: typeof AuthenticatedAdminBadgesRoute
  AuthenticatedAdminBibliothequeRoute: typeof AuthenticatedAdminBibliothequeRoute
  AuthenticatedAdminCahierDeTexteRoute: typeof AuthenticatedAdminCahierDeTexteRoute
  AuthenticatedAdminEtudiantsRoute: typeof AuthenticatedAdminEtudiantsRoute
  AuthenticatedAdminGroupesRoute: typeof AuthenticatedAdminGroupesRoute
  AuthenticatedAdminMissionsRoute: typeof AuthenticatedAdminMissionsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminParcoursRoute: typeof AuthenticatedAdminParcoursRoute
  AuthenticatedAdminPartenairesRoute: typeof AuthenticatedAdminPartenairesRoute
  AuthenticatedAdminProfesseursRoute: typeof AuthenticatedAdminProfesseursRoute
  AuthenticatedAdminProlongationsRoute: typeof AuthenticatedAdminProlongationsRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminValidationsRoute: typeof AuthenticatedAdminValidationsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBadgesRoute: AuthenticatedAdminBadgesRoute,
  AuthenticatedAdminBibliothequeRoute: AuthenticatedAdminBibliothequeRoute,
  AuthenticatedAdminCahierDeTexteRoute: AuthenticatedAdminCahierDeTexteRoute,
  AuthenticatedAdminEtudiantsRoute: AuthenticatedAdminEtudiantsRoute,
  AuthenticatedAdminGroupesRoute: AuthenticatedAdminGroupesRoute,
  AuthenticatedAdminMissionsRoute: AuthenticatedAdminMissionsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
  AuthenticatedAdminParcoursRoute: AuthenticatedAdminParcoursRoute,
  AuthenticatedAdminPartenairesRoute: AuthenticatedAdminPartenairesRoute,
  AuthenticatedAdminProfesseursRoute: AuthenticatedAdminProfesseursRoute,
  AuthenticatedAdminProlongationsRoute: AuthenticatedAdminProlongationsRoute,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminValidationsRoute: AuthenticatedAdminValidationsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEtudiantRouteChildren {
  AuthenticatedEtudiantBadgesRoute: typeof AuthenticatedEtudiantBadgesRoute
  AuthenticatedEtudiantCarnetRoute: typeof AuthenticatedEtudiantCarnetRoute
  AuthenticatedEtudiantGroupeRoute: typeof AuthenticatedEtudiantGroupeRoute
  AuthenticatedEtudiantNotificationsRoute: typeof AuthenticatedEtudiantNotificationsRoute
  AuthenticatedEtudiantParcoursRoute: typeof AuthenticatedEtudiantParcoursRoute
  AuthenticatedEtudiantSessionsRoute: typeof AuthenticatedEtudiantSessionsRoute
}

const AuthenticatedEtudiantRouteChildren: AuthenticatedEtudiantRouteChildren = {
  AuthenticatedEtudiantBadgesRoute: AuthenticatedEtudiantBadgesRoute,
  AuthenticatedEtudiantCarnetRoute: AuthenticatedEtudiantCarnetRoute,
  AuthenticatedEtudiantGroupeRoute: AuthenticatedEtudiantGroupeRoute,
  AuthenticatedEtudiantNotificationsRoute:
    AuthenticatedEtudiantNotificationsRoute,
  AuthenticatedEtudiantParcoursRoute: AuthenticatedEtudiantParcoursRoute,
  AuthenticatedEtudiantSessionsRoute: AuthenticatedEtudiantSessionsRoute,
}

const AuthenticatedEtudiantRouteWithChildren =
  AuthenticatedEtudiantRoute._addFileChildren(
    AuthenticatedEtudiantRouteChildren,
  )

interface AuthenticatedPartenaireRouteChildren {
  AuthenticatedPartenaireEtudiantsRoute: typeof AuthenticatedPartenaireEtudiantsRoute
  AuthenticatedPartenaireMissionsRoute: typeof AuthenticatedPartenaireMissionsRoute
  AuthenticatedPartenaireParcoursRoute: typeof AuthenticatedPartenaireParcoursRoute
}

const AuthenticatedPartenaireRouteChildren: AuthenticatedPartenaireRouteChildren =
  {
    AuthenticatedPartenaireEtudiantsRoute:
      AuthenticatedPartenaireEtudiantsRoute,
    AuthenticatedPartenaireMissionsRoute: AuthenticatedPartenaireMissionsRoute,
    AuthenticatedPartenaireParcoursRoute: AuthenticatedPartenaireParcoursRoute,
  }

const AuthenticatedPartenaireRouteWithChildren =
  AuthenticatedPartenaireRoute._addFileChildren(
    AuthenticatedPartenaireRouteChildren,
  )

interface AuthenticatedProfesseurParcoursRouteChildren {
  AuthenticatedProfesseurParcoursParcoursIdRoute: typeof AuthenticatedProfesseurParcoursParcoursIdRoute
}

const AuthenticatedProfesseurParcoursRouteChildren: AuthenticatedProfesseurParcoursRouteChildren =
  {
    AuthenticatedProfesseurParcoursParcoursIdRoute:
      AuthenticatedProfesseurParcoursParcoursIdRoute,
  }

const AuthenticatedProfesseurParcoursRouteWithChildren =
  AuthenticatedProfesseurParcoursRoute._addFileChildren(
    AuthenticatedProfesseurParcoursRouteChildren,
  )

interface AuthenticatedProfesseurRouteChildren {
  AuthenticatedProfesseurEtudiantsRoute: typeof AuthenticatedProfesseurEtudiantsRoute
  AuthenticatedProfesseurMissionsRoute: typeof AuthenticatedProfesseurMissionsRoute
  AuthenticatedProfesseurModulesRoute: typeof AuthenticatedProfesseurModulesRoute
  AuthenticatedProfesseurParcoursRoute: typeof AuthenticatedProfesseurParcoursRouteWithChildren
  AuthenticatedProfesseurPartenairesRoute: typeof AuthenticatedProfesseurPartenairesRoute
  AuthenticatedProfesseurProlongationsRoute: typeof AuthenticatedProfesseurProlongationsRoute
  AuthenticatedProfesseurValidationsRoute: typeof AuthenticatedProfesseurValidationsRoute
  AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute: typeof AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute
}

const AuthenticatedProfesseurRouteChildren: AuthenticatedProfesseurRouteChildren =
  {
    AuthenticatedProfesseurEtudiantsRoute:
      AuthenticatedProfesseurEtudiantsRoute,
    AuthenticatedProfesseurMissionsRoute: AuthenticatedProfesseurMissionsRoute,
    AuthenticatedProfesseurModulesRoute: AuthenticatedProfesseurModulesRoute,
    AuthenticatedProfesseurParcoursRoute:
      AuthenticatedProfesseurParcoursRouteWithChildren,
    AuthenticatedProfesseurPartenairesRoute:
      AuthenticatedProfesseurPartenairesRoute,
    AuthenticatedProfesseurProlongationsRoute:
      AuthenticatedProfesseurProlongationsRoute,
    AuthenticatedProfesseurValidationsRoute:
      AuthenticatedProfesseurValidationsRoute,
    AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute:
      AuthenticatedProfesseurCarnetEtudiantIdParcoursIdRoute,
  }

const AuthenticatedProfesseurRouteWithChildren =
  AuthenticatedProfesseurRoute._addFileChildren(
    AuthenticatedProfesseurRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedEtudiantRoute: typeof AuthenticatedEtudiantRouteWithChildren
  AuthenticatedPartenaireRoute: typeof AuthenticatedPartenaireRouteWithChildren
  AuthenticatedProfesseurRoute: typeof AuthenticatedProfesseurRouteWithChildren
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedEtudiantRoute: AuthenticatedEtudiantRouteWithChildren,
  AuthenticatedPartenaireRoute: AuthenticatedPartenaireRouteWithChildren,
  AuthenticatedProfesseurRoute: AuthenticatedProfesseurRouteWithChildren,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
